# Generated by Django 5.0 on 2023-12-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apostas',
            new_name='Apostas_1',
        ),
    ]
